### PR TITLE
Update for different names as "eno1"

### PR DESCRIPTION
**Pull request by TriMoon**
Fix grep command to allow for different network-card names.

PS: Would be so much easier, if you also put the files as separate files in your repo, so we can clone it and use the files directly...

### CODE REVIEW

**Comment by TriMoon** [comment]
I haven't tested your units yet, but the message it looks for seems present in a previous boot of my system...
I checked with `journalctl -b -1 --grep 'igc.*: PCIe link lost, device now detached'`

**Comment by TriMoon** [comment]
That last commit changing file permissions (a +x) was me also, just using the git-cli instead of the web :wink: 

The units with bash-script is now running on my system, lets hope it fixes these drop-outs. :+1:

**Comment by TriMoon** [comment]
Maybe replace the scripts logic with something similar to what hes doing with `journalctl`.
No timer needed either, as it's a infinite loop that loops over the log messages?

This guy is checking for a different error message, but maybe you could check for both?

https://www.reddit.com/r/buildapc/comments/xypn1m/comment/ki8miwd/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by ShigShag** [comment]
I tried the `journalctl` method and it did not work for me. Rest looks good though, thank you.

**Comment by TriMoon** [comment]
@ShigShag 
> I tried the `journalctl` method and it did not work for me. Rest looks good though, thank you.

I have made that in my repo: https://gitlab.com/trimoon-inc/asus_x670e_ethernet_fix
Feel free to sync with it :wink: 

PS: Would be great if you could post it in that reddit thread also, because i can't... :+1: 
PPS: If you want i could add you as collaborator/member on my repo too, i send you an email invite...

**Pull request merged**
